### PR TITLE
SCRC-597 Added .pylint file.

### PR DESCRIPTION
**Pull request by mrow84**

### CODE REVIEW

**Comment by bobturneruk** [comment]
Please add this boilerplate. https://github.com/ScottishCovidResponse/simple_network_sim#static-analysis

I will need to change codacy settings post-merge.

**Review by bobturneruk — APPROVED** [review]

**Review by bobturneruk — APPROVED** [review]

**Comment by bobturneruk** [comment]
I'm going to merge now so I can click the thing in codacy to use the config file.

**Comment by bobturneruk** [comment]
Good catch @mrow84 !

**Comment by mrow84** [comment]
Just snuck in a fix to the link in the README, which I had gotten wrong. Looks like it made it in.

**Comment by bobturneruk** [comment]
OK - clicked the thing. Should be using the config.

**Pull request merged**
