### PR TITLE
Add file formats to packages in setup.py

### PR DESCRIPTION
**Pull request by AlexRobson**
Tiny MR to update `setup.py`. 

IIUC (been a long time since i've worked much in python so maybe misunderstanding something here ...!), conda is creating this environment fine, but when installing it for use from another package it throws an error:
```
>>> import data_pipeline_api
>>> import data_pipeline_api.file_formats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'data_pipeline_api.file_formats'
```

This is after installing by `pip` within the conda environment:

```
(data_pipeline_api) alexrobson@Charybdis data_pipeline_api % which pip3              
/Users/alexrobson/miniconda/envs/data_pipeline_api/bin/pip3
```

Can see that it's not included with the conda packages:

```
/Users/alexrobson/miniconda/pkgs/data_pipeline_api-0.2.0-py_0/site-packages/data_pipeline_api
alexrobson@Charybdis data_pipeline_api % ls -lah
total 64
drwxr-xr-x  8 alexrobson  staff   256B  5 Jul 18:14 .
drwxr-xr-x  4 alexrobson  staff   128B  5 Jul 18:14 ..
-rw-rw-r--  2 alexrobson  staff   6.7K  3 Jul 14:33 file_api.py
-rw-rw-r--  2 alexrobson  staff   570B  3 Jul 14:33 metadata.py
-rw-rw-r--  2 alexrobson  staff   1.2K  3 Jul 14:33 metadata_store.py
-rw-rw-r--  2 alexrobson  staff   666B  3 Jul 14:33 overrides.py
-rw-rw-r--  2 alexrobson  staff   595B  3 Jul 14:33 simple_network_sim_api.py
-rw-rw-r--  2 alexrobson  staff   6.3K  3 Jul 14:33 standard_api.py
alexrobson@Charybdis data_pipeline_api % head standard_api.py 
from io import TextIOWrapper
from pathlib import Path
from contextlib import contextmanager
import numpy as np
import pandas as pd
from data_pipeline_api.file_api import FileAPI
from data_pipeline_api.file_formats import parameter_file, object_file <-- Fails


class StandardAPI(FileAPI):

```

IIUC, as  `file_formats` is a submodule, it needs to be added to `setup.py` to be installed, so  I (think) that this is needed to work with `data_pipeline_api` 

EDIT: Edited to include the error

### CODE REVIEW

**Review by mrow84 — APPROVED** [review]
Looks reasonable to me, but @aflag and @bobturneruk are our resident experts on the packaging process. I will approve, but it might be worth just checking with one of them for a more informed opinion.

**Comment by bobturneruk** [comment]
Is the sub-package folder necessary?

**Comment by AlexRobson** [comment]
> Is the sub-package folder necessary?

Is this to me? Because I do not know :). I raised this PR was because we are wrapping the julia set-up around it and found it was erroring as above. I used to use python, but it's been a while, and I didn't work with any of the packaging side, so I don't know what's best here.

**Comment by bobturneruk** [comment]
OK! I'm going to merge as I don't want to hold things up. I've raised a separate issue on package / folder structure (https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/566). I don't think this will break anything downstream.

**Review by bobturneruk — APPROVED** [review]

**Pull request merged**
