### PR TITLE
Fix Semver and Pytest deprecation warnings

### LINKED ISSUE #777: PyTest `yield_fixture` is deprecated, use `fixture` instead in unit tests.
In test running:

```bash
SCRC/data_pipeline_api/tests/registry/test_upload.py:23: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(autouse=True)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

### LINKED ISSUE #778: Move from `semver.parse_version_info` to `semver.VersionInfo.parse` for future move to semver v3
```bash
DeprecationWarning: Function 'semver.parse_version_info' is deprecated. Deprecated since version 2.10.0.  This function will be removed in semver 3. Use 'semver.VersionInfo.parse' instead.
```

### PR DESCRIPTION
**Pull request by kzscisoft**
This fixes the deprecation warnings given by PyTest and Semver:

`pytest.yield_fixture` -> `pytest.fixture`
`semver.parse_version_info` -> `semver.VersionInfo.parse`

Closes https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/778
Closes https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/777

### CODE REVIEW

**Comment by DennisReddyhoff** [comment]
No deprecation warnings on running Pytest but got these:

image

Not totally sure what its related to, will discuss with Bob shortly

**Review by DennisReddyhoff — APPROVED** [review]
This PR fixes the deprecation warnings as intended, the errors are related to a separate issue

**Comment by bobturneruk** [comment]
We probably don't need the egg stuff?

**Comment by bobturneruk** [comment]
Suggest:

- Update docs to reflect install should be via `git` or `pip install git+`
- Remove access*yaml s
- Remove all eggy

**Comment by bobturneruk** [comment]
Merge if passes locally in Linux

**Review by bobturneruk — APPROVED** [review]
See comments, but OK - this will give us a Linux version that passes tests. CI, release CI and other OS compatibility to be added in future.

**Comment by kzscisoft** [comment]
@bobturneruk are we ok to press "merge" now then?

**Comment by bobturneruk** [comment]
Once @DennisReddyhoff has make changes as per comments above. In future we should keep branches focussed and separate. I suggest that ordinarily the originator of a PR should do the merge, but in this case best if it's Dennis.

**Review by bobturneruk — APPROVED** [review]
Good stuff.

**Pull request merged**
