### PR TITLE
Distributions returned from api to use specified random generator

### PR DESCRIPTION
**Pull request by vinopm**
All distributions returned from api to use specified random generator + some clean up

### CODE REVIEW

**Comment by vinopm** [comment]
@johnnonweiler

**Review by johnnonweiler — APPROVED** [review]
This looks good for now.  (And I'll be very happy if we see it working today!)

I agree with the comments in the code along the lines of "this is a bit of a hack", and think it might make sense to review this in future, and look again at moving the RNG outside of the StandardAPI.

**Review by rtblackwell — APPROVED** [review]

**Comment by vinopm** [comment]
@mrow84 Thanks for your feedback. The data registry download script seems to expect the config.yaml file to have data_directory within run_metadata? It fails with an error when data_directory is specified at the top level and when run_metadata does not contain data_directory

**Comment by mrow84** [comment]
Ah yeah, you're right, the download script does take it from the run_metadata. Does the java implementation of the file API now just use the data_directory in the run_metadata section internally? If so I will change the python implementation accordingly and update the spec. I wonder whether we should move the other parameters (e.g. run_id) inside there as well? The output run_id might be different to the input one, but I think that is fine.

**Comment by vinopm** [comment]
@mrow84 Yeah, i just changed the java api in this PR to pick up the data_directory from within run_metadata. The other params such as run_id are still at the root level. We could move it, not sure what would make most sense from the API perspective

**Comment by mrow84** [comment]
Ok well in the first instance I will move the data_directory in the same way you have here. We can perhaps defer the rest to a later time.

**Comment by vinopm** [comment]
Agreed, thanks @mrow84

**Pull request merged**
