### PR TITLE
Description and issues into File API

### PR DESCRIPTION
**Pull request by vinopm**

### CODE REVIEW

**Comment by vinopm** [comment]
@johnnonweiler FYI if you're interested in reviewing

**Review by mrow84 — APPROVED** [review]

**Comment by johnnonweiler** [comment]
@vinopm Thanks for tagging me on these PRs - It's helpful for me to see what is going on. (I'm happy that things are getting merged without my review).

What is this feature?  (I just had another look at the doc in Teams describing the FileAPI, and there was no mention of "issues".)

**Comment by vinopm** [comment]
@johnnonweiler It is documented in the 'Standard API' document. The python implementation of the File API is very generic in the sense that it just takes a Map as the parameter input for metadata, whereas in the Java implementation the expected fields are coded explicitly in the MetadataItem class. 

Please see https://teams.microsoft.com/l/file/03af05f8-df00-417b-ba73-b152606c0cca?tenantId=6e725c29-763a-4f50-81f2-2e254f0133c8&fileType=docx&objectUrl=https%3A%2F%2Fgla.sharepoint.com%2Fsites%2FScottishCOVID-19ResearchConsortium%2FShared%2520Documents%2FGeneral%2FCollaboration%2Fdata%2520pipeline%2520API%2F3.%2520Standardised%2520data%2520type%2520API.docx&baseUrl=https%3A%2F%2Fgla.sharepoint.com%2Fsites%2FScottishCOVID-19ResearchConsortium&serviceName=aggregatefiles

**Comment by johnnonweiler** [comment]
@vinopm Thank you.  That's helpful.  This makes more sense to me now.

**Pull request merged**
