### PR TITLE
Stop using `src` folder structure

### PR DESCRIPTION
**Pull request by bobturneruk**
Supersedes https://github.com/ScottishCovidResponse/data_pipeline_api/pull/7

### CODE REVIEW

**Comment by bobturneruk** [comment]
Reviewers - please merge this if you're happy with it - don't wait for me.

**Comment by aflag** [comment]
You will need to remove this line from setup.py now: https://github.com/ScottishCovidResponse/data_pipeline_api/blob/6201e4c78fd422e684acb85272834e589be729e8/setup.py#L17

**Comment by bobturneruk** [comment]
Done ^

**Review by mrow84 — COMMENTED** [review]
Do we have to change/remove this: https://github.com/ScottishCovidResponse/data_pipeline_api/blob/077716f37483b83d9140566f18564386e0d4d825/setup.py#L17 - I guess it exists on master but looks like it doesn't on your branch, but maybe that is because you're branched from an older commit?

**Review by mrow84 — APPROVED** [review]

**Pull request merged**
