### PR TITLE
Python only

### LINKED ISSUE #784: Remove C++ and Java from data_pipeline_api repository.

### PR DESCRIPTION
**Pull request by bobturneruk**
Delete all non-python stuff from this repo.

Resolves https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/784.

Merge after https://github.com/ScottishCovidResponse/data_pipeline_api/pull/112 fixes CI.

### CODE REVIEW

**Comment by bobturneruk** [comment]
Actually this looks like it largely passes the remaining CI, so could be merged on approval.

**Comment by bobturneruk** [comment]
Now it's not passing (after a rebase).

**Comment by bobturneruk** [comment]
Tests pass on Ubuntu, fail on Windows (in my hands).

**Comment by kzscisoft** [comment]
Confirmed that `cpp_bindings` folder has been removed, my understanding this was all the C++ content within this repository so I can approve this.

**Review by kzscisoft — APPROVED** [review]

**Comment by richardreeve** [comment]
@bobturneruk / @DennisReddyhoff - I think that travis needs to be pointed at travis-ci.com rather than travis-ci.org (the latter has closed down) to get the travis to work here? At some later date we need to migrate the testing on this repo to github actions though...

**Comment by bobturneruk** [comment]
This would resolve the above https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/776

**Comment by richardreeve** [comment]
Okay - we probably need to do that separately. I'll just merge this now.

**Pull request merged**
